### PR TITLE
issue: doesn't support libraries

### PR DESCRIPTION
**Pull request by Ian2012**
# Description

This xblock is not compatible with Libraries.

**What happens if you try to use this in a library?**

The flow control xblock expects the question id of the problem, the issue with libraries is that the problem id is dynamic based on the random problem/problems generated by a library for a given user.

**In which version of the platform have you tried this?**

Limonero master

**Do you get any particular error when trying?**

No, the flow-control xblock doesn't detect any case.

I cannot add all the problems ids for all the problem id in the library because that will work just with some cases but not for all of them.

### Note

As I cannot create issues in this repo, I just opened this PR.

### CODE REVIEW

**Comment by felipemontoya** [comment]
@Ian2012 could you give me some more info please?

- What happens if you try to use this in a library?
- In which version of the platform have you tried this?
- Do you get any particular error when trying?

**Comment by Ian2012** [comment]
@felipemontoya I've updated the PR

**Comment by felipemontoya** [comment]
Thanks @Ian2012 thanks for the extra info.

Definitely looks like a major feature. For a moment I thought that would be something we needed to add a few fields to support, but it looks like a design limitation now.

Alternatively, we could add the note to the readme, but it should be the opposite note. That this xblock in fact can not be used with libraries due to the lack of ID. What do you think?

**Comment by Ian2012** [comment]
I'm not sure, but I think we can update this Xblock to add support for libraries without breaking changes.

Add a boolean field or verify if the problem id corresponds to a library and perform the corresponding action based on it. Or there may be the case that we definitively need a breaking change. In any case, we need some exploration.

I will be updating this PR, but can the issues tab be activated?

**Comment by felipemontoya** [comment]
I think I removed the issues tab because we were not looking into it, so people reported issues and it sat in oblivion for months. I only want to open the tab again when I have a plan for how we will respond to that. In the meantime this PR is a good place to keep this conversation.

**Pull request closed without merging**
